# fly.toml app configuration file generated for edbox on 2023-08-23T21:49:32+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "edbox"
primary_region = "sin"

[build]

[http_service]
  internal_port = 5080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
